config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

   resources :articles, :only => [:new, :create, :destroy, :index]

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:destroy]

def index
  @articles = Article.all
end

def new
  @article = Article.new
end

def create
  @article = Article.create!(blog_master_params)
  flash[:notice] = "New article created."
  redirect_to root_path
end

def destroy
  @article.destroy
  flash[:notice] = @article.title + " was deleted."
  redirect_to root_path
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_master_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/calculator.rb
class Calculator
 def push(arg)
  @arg ||= []
  @arg << arg
 end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if  @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this blog_master from being saved:</h2>
      <ul>
      <%  @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title, "Article Title:" %><br>
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :content, "Artical Content :" %><br>
    <%= f.text_field :content %>
  </div>
  <%= f.submit "Create" , class: "btn btn-large btn-primary"  %>
  </div>
<% end %>

app/views/articles/index.html.erb
<%= flash[:notice] %>
<table class="table">
 <tr>
  <th>Title</th>
  <th>Content</th>
  <th>Action</th>
 </tr>
<% for article in @articles %>
 <tr>
  <td><%=h article.title %></td>
  <td><%=h article.content %></td>
  <td> <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-primary"  %></td>
 </tr>
<% end %>
</table>
<%= link_to "Create", new_article_path, class: "btn btn-primary" %>

app/views/articles/new.html.erb
<div class="row">
 <div class="span12 offset2" , id="profile">
  <h1>Create New Artical</h1>
    <%= render 'form' %>
    </br>
      <%= link_to 'Back', root_path, class: "btn btn-primary"  %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CucumberTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>